/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dual;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Nick
 */
public class GameScreen extends javax.swing.JPanel {
  float shootTimer = 0.0f;
  double drawCountdown = 10*Math.random()%10 * 1000;
  boolean gameActive = true;
  boolean shotsFired = false;
  long delta;
  long thisLoop = System.nanoTime()/1000000;
    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
        fireButton.setBackground(Color.red);
    }
public void gameLoop(){
       
     if(!shotsFired){
        
        long timeLoop=System.nanoTime()/1000000;
        delta = timeLoop - thisLoop; 
        thisLoop = timeLoop;
        
       if(drawCountdown <=0 && !shotsFired){
            fireButton.setBackground(Color.green);
            shootTimer+=delta; //times by loops per second
        }
        else{
            drawCountdown-=delta; //times by loops per second
        }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fireButton = new javax.swing.JButton();
        speedLabel = new javax.swing.JLabel();

        fireButton.setText("Fire");
        fireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireButtonActionPerformed(evt);
            }
        });

        speedLabel.setText("Speed:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(fireButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(speedLabel)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(speedLabel)
                .addGap(78, 78, 78)
                .addComponent(fireButton)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
        if(drawCountdown > 0){
            System.out.println("Miss");
            shotsFired=true;
        }
        else if(shotsFired){
            System.out.println("Click");
        }
        else{
            System.out.println("Bang Bang");
            shotsFired = true;
            speedLabel.setText(""+shootTimer/1000);
            fireButton.setBackground(Color.red);
        }
    }//GEN-LAST:event_fireButtonActionPerformed


public static void main(String[] args){
    JFrame frame = new JFrame();
   
    GameScreen gs = new GameScreen();
    frame.setSize(500, 500);
    frame.setVisible(true);
    frame.add(gs);
    gs.setVisible(true);
    while(gs.gameActive){
        gs.gameLoop();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fireButton;
    private javax.swing.JLabel speedLabel;
    // End of variables declaration//GEN-END:variables
}
